####################################################################################################
# Pipelex Inference Backends Configuration
####################################################################################################
#
# This file configures the inference backends available to Pipelex.
# Each backend connects to a different AI service provider (OpenAI, Anthropic, Google, etc.).
#
# Documentation: https://docs.pipelex.com
# Support: https://go.pipelex.com/discord
#
####################################################################################################

[pipelex_inference]
display_name = "⭐ Pipelex Inference"
enabled = false
endpoint = "https://inference.pipelex.com/v1"
api_key = "${PIPELEX_INFERENCE_API_KEY}"

[azure_openai]
display_name = "Azure OpenAI"
enabled = false
endpoint = "${AZURE_API_BASE}"
api_key = "${AZURE_API_KEY}"
api_version = "${AZURE_API_VERSION}"

[bedrock]
display_name = "Amazon Bedrock"
enabled = false
aws_region = "${AWS_REGION}"

[google]
display_name = "Google AI"
enabled = false
api_key = "${GOOGLE_API_KEY}"

[vertexai]
display_name = "Google Vertex AI"
enabled = false
gcp_project_id = "${GCP_PROJECT_ID}"
gcp_location = "${GCP_LOCATION}"
gcp_credentials_file_path = "${GCP_CREDENTIALS_FILE_PATH}"

[openai]
display_name = "OpenAI"
enabled = false
api_key = "${OPENAI_API_KEY}"

[anthropic]
enabled = false
api_key = "${ANTHROPIC_API_KEY}"
claude_4_tokens_limit = 8192

[mistral]
display_name = "Mistral AI"
enabled = false
api_key = "${MISTRAL_API_KEY}"

[xai]
display_name = "xAI"
enabled = false
endpoint = "https://api.x.ai/v1"
api_key = "${XAI_API_KEY}"

[ollama]
enabled = false
endpoint = "http://localhost:11434/v1"

[blackboxai]
display_name = "BlackBox AI"
enabled = true
endpoint = "https://api.blackbox.ai/v1"
api_key = "${BLACKBOX_API_KEY}"

[fal]
display_name = "FAL"
enabled = false
api_key = "${FAL_API_KEY}"

[internal] # software-only backend, runs internally, without AI
enabled = true
