################################################################################
# Anthropic Backend Configuration
################################################################################
#
# This file defines the model specifications for Anthropic Claude models.
# It contains model definitions for various Claude language models
# accessible through the Anthropic API.
#
# Configuration structure:
# - Each model is defined in its own section with the model name as the header
# - Headers with dots must be quoted (e.g., ["claude-3.5-sonnet"])
# - Model costs are in USD per million tokens (input/output)
#
# Documentation: https://docs.pipelex.com
# Support: https://go.pipelex.com/discord
#
################################################################################

################################################################################
# MODEL DEFAULTS
################################################################################

[defaults]
model_type = "llm"
sdk = "anthropic"
prompting_target = "anthropic"

################################################################################
# LANGUAGE MODELS
################################################################################

# --- Claude 3 Series ----------------------------------------------------------
[claude-3-haiku]
model_id = "claude-3-haiku-20240307"
max_tokens = 4096
inputs = ["text", "images"]
outputs = ["text", "structured"]
max_prompt_images = 100
costs = { input = 0.25, output = 1.25 }

[claude-3-opus]
model_id = "claude-3-opus-20240229"
max_tokens = 4096
inputs = ["text", "images"]
outputs = ["text", "structured"]
max_prompt_images = 100
costs = { input = 15.0, output = 75.0 }

# --- Claude 3.7 Series --------------------------------------------------------
["claude-3.7-sonnet"]
model_id = "claude-3-7-sonnet-20250219"
max_tokens = 8192
inputs = ["text", "images"]
outputs = ["text", "structured"]
max_prompt_images = 100
costs = { input = 3.0, output = 15.0 }

# --- Claude 4 Series ----------------------------------------------------------
[claude-4-sonnet]
model_id = "claude-sonnet-4-20250514"
max_tokens = 64000
inputs = ["text", "images"]
outputs = ["text", "structured"]
max_prompt_images = 100
costs = { input = 3.0, output = 15.0 }

[claude-4-opus]
model_id = "claude-opus-4-20250514"
max_tokens = 32000
inputs = ["text", "images"]
outputs = ["text", "structured"]
max_prompt_images = 100
costs = { input = 3.0, output = 15.0 }

# --- Claude 4.1 Series --------------------------------------------------------
["claude-4.1-opus"]
model_id = "claude-opus-4-1-20250805"
max_tokens = 32000
inputs = ["text", "images"]
outputs = ["text", "structured"]
max_prompt_images = 100
costs = { input = 3.0, output = 15.0 }

# --- Claude 4.5 Series --------------------------------------------------------
["claude-4.5-sonnet"]
model_id = "claude-sonnet-4-5-20250929"
max_tokens = 64000
inputs = ["text", "images"]
outputs = ["text", "structured"]
max_prompt_images = 100
costs = { input = 3.0, output = 15.0 }
