################################################################################
# XAI Backend Configuration
################################################################################
#
# This file defines the model specifications for XAI (formerly Twitter AI) models.
# It contains model definitions for Grok language models
# accessible through the XAI API.
#
# Configuration structure:
# - Each model is defined in its own section with the model name as the header
# - Headers with dots must be quoted (e.g., ["grok-3"])
# - Model costs are in USD per million tokens (input/output)
#
# Documentation: https://docs.pipelex.com
# Support: https://go.pipelex.com/discord
#
################################################################################

################################################################################
# MODEL DEFAULTS
################################################################################

[defaults]
model_type = "llm"
sdk = "openai"
prompting_target = "anthropic"

################################################################################
# LANGUAGE MODELS
################################################################################

# --- Grok 3 Series ------------------------------------------------------------
[grok-3]
model_id = "grok-3"
inputs = ["text"]
outputs = ["text"]
costs = { input = 3, output = 15 }

[grok-3-mini]
model_id = "grok-3-mini"
inputs = ["text"]
outputs = ["text"]
costs = { input = 0.3, output = 0.5 }

[grok-3-fast]
model_id = "grok-3-fast-latest"
inputs = ["text"]
outputs = ["text"]
costs = { input = 5, output = 25 }

[grok-3-mini-fast]
model_id = "grok-3-mini-fast-latest"
inputs = ["text"]
outputs = ["text"]
costs = { input = 0.15, output = 4 }

